global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.CQRS;
global using Basket.API.Models;
global using FluentValidation;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.Handler;
// global using Basket.API.Data;
// global using Marten.Pagination;
// global using Marten;
// global using Basket.API.Exceptions;